### ISSUE TITLE
【依頼】ProtoSpace挙動確認自身のProtoSpaceのURL（本番環境）

### ISSUE THREAD

**Issue by honda-gentuki** [honda-gentuki/protospace-37854#1]
https://protospace-37854.herokuapp.com/

**Comment by shodai-ito** [comment]
@honda-gentuki さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
